import java.util.Scanner;
public class TA_Algo {
    static Scanner sc = new Scanner(System.in);
    
    static String Stack [][] = new String [1][4];
    static int hargaE[] = {870000,1150000,900000}; 
    static int hargaB[] = {1640000,2250000,1800000}; 
    static int top = 0;
    public static void main(String[] args) {
        while(true){
            System.out.println("--------[ HAMENGKUBUWONO AIRPORT YOGYAKARTA ]---------");
            System.out.println(" ");
            System.out.println("------------------[ Menu Utama ]--------------------\n");
            System.out.println("1.Pendaftaran Akun Calon Penumpang");
            System.out.println("2.Pilih Rute Penerbangan");
            System.out.println("0.Keluar Program");
            System.out.print("\nPilih Menu : ");
            int pilihan = sc.nextInt();
            sc.nextLine();
            
            if(pilihan == 1){
                pendaftaran();
            }else if(pilihan == 2){
                RUTEpenerbangan();
                pop();
            }else if (pilihan == 0){
                System.out.println("============== [ PROGRAM SELESAI ]==================");
                break;
            }else{
                System.out.println("Maaf anda salah menginput ");
            }
        }
    }
    public static void RUTEpenerbangan(){
        System.out.println("_______________________________________________________________________________________");
        System.out.println("| No |     Asal     |     Tujuan    |   Harga Tiket Ekonomi    |   Harga Tiket Bisnis  |");
        System.out.println("|----|--------------|---------------|--------------------------|-----------------------|");
        System.out.println("|  1 | Yogyakarta   | Jakarta       |      Rp.870.000          |   Rp.1.640.000        |");
        System.out.println("|  2 | Yogyakarta   | Surabaya      |      Rp.1.150.000        |   Rp.2.550.000        |");
        System.out.println("|  3 | Jakarta      | Yogyakarta    |      Rp.870.000          |   Rp.1.640.000        |");
        System.out.println("|  4 | Jakarta      | Surabaya      |      Rp.900.000          |   Rp.1.800.000        |");
        System.out.println("|  5 | Surabaya     | Yogyakarta    |      Rp.1.150.000        |   Rp.2.550.000        |");
        System.out.println("|  6 | Surabaya     | Jakarta       |      Rp.900.000          |   Rp.1.800.000        |");
        System.out.println("|____|______________|_______________|__________________________|_______________________|");
        System.out.println();
        System.out.println("1.Sekali Jalan ");
        System.out.println("2.Pulang-Pergi ");
        System.out.print("Pilih : ");
        int rute = sc.nextInt();
        if(rute == 1){
        System.out.println("Masukan Tanggal Keberangkatan Dengan Format DD/MM/YYYY");
        System.out.print("Tanggal Keberangkatan : ");
        String tanggal = sc.next();
        System.out.println("[ Asal Keberangkatan ]");
        System.out.println("1.Yogyakarta");
        System.out.println("2.Jakarta");
        System.out.println("3.Surabaya");
        System.out.print("pilih : ");
        int pilihAsal = sc.nextInt();
        System.out.println("[ Tujuan Keberangkatan ]");
        System.out.println("1.Yogyakarta");
        System.out.println("2.Jakarta");
        System.out.println("3.Surabaya");
        System.out.print("pilih : ");
        int pilihTujuan = sc.nextInt();
        System.out.println("Pilih Kelas Maskapai"); 
        System.out.println("1.Ekonomi");
        System.out.println("2.Bisnis ");
        System.out.print("Pilih : ");
        int pilihKelas = sc.nextInt();
        if(pilihAsal == 1 && pilihTujuan == 2 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[0]*20/100;
            int HK = (hargaE[0]-diskon)*kecil;
            int HD = hargaE[0]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Jakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if (pilihAsal == 1 && pilihTujuan == 3 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaE[1]*20/100;
            int HK = (hargaE[1]-diskon)*kecil;
            int HD = hargaE[1]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 2 && pilihTujuan == 1 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[0]*20/100;
            int HK = (hargaE[0]-diskon)*kecil;
            int HD = hargaE[0]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Jakarta - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 2 && pilihTujuan == 3 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaE[2]*20/100;
            int HK = (hargaE[2]-diskon)*kecil;
            int HD = hargaE[2]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Jakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 3 && pilihTujuan == 1 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya  - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaE[1]*20/100;
            int HK = (hargaE[1]-diskon)*kecil;
            int HD = hargaE[1]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Surabaya - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 3 && pilihTujuan == 2 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya  - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaE[2]*20/100;
            int HK = (hargaE[2]-diskon)*kecil;
            int HD = hargaE[2]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Surabaya - Jakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 1 && pilihTujuan == 2 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta  - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[0]*20/100;
            int HK = (hargaB[0]-diskon)*kecil;
            int HD = hargaB[0]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Jakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 1 && pilihTujuan == 3 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta  - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[1]*20/100;
            int HK = (hargaB[1]-diskon)*kecil;
            int HD = hargaB[1]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 2 && pilihTujuan == 1 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta  - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[0]*20/100;
            int HK = (hargaB[0]-diskon)*kecil;
            int HD = hargaB[0]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Jakarta - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 2 && pilihTujuan == 3 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta  - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[2]*20/100;
            int HK = (hargaB[2]-diskon)*kecil;
            int HD = hargaB[2]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Jakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 3 && pilihTujuan == 1 && pilihKelas == 2){
           System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya  - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[1]*20/100;
            int HK = (hargaB[1]-diskon)*kecil;
            int HD = hargaB[1]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Surabaya - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 3 && pilihTujuan == 2 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya  - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[2]*20/100;
            int HK = (hargaB[2]-diskon)*kecil;
            int HD = hargaB[2]*dewasa;
            int TH = HK+HD;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggal);
            System.out.println("Tujuan Penerbangan : Surabaya - Jakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else{
            System.out.println("Maaf,inputan anda salah");
        }
        }else if(rute == 2){
        System.out.println("Masukan Tanggal Keberangkatan & Pulang Dengan Format DD/MM/YYYY");
        System.out.print("Tanggal Keberangkatan : ");
        String tanggalK = sc.next();
        System.out.print("Tanggal Pulang : ");
        String tanggalP = sc.next();
        System.out.println("[ Asal Keberangkatan ]");
        System.out.println("1.Yogyakarta");
        System.out.println("2.Jakarta");
        System.out.println("3.Surabaya");
        System.out.print("pilih : ");
        int pilihAsal = sc.nextInt();
        System.out.println("[ Tujuan Keberangkatan ]");
        System.out.println("1.Yogyakarta");
        System.out.println("2.Jakarta");
        System.out.println("3.Surabaya");
        System.out.print("pilih : ");
        int pilihTujuan = sc.nextInt();
        System.out.println("Pilih Kelas Maskapai"); 
        System.out.println("1.Ekonomi");
        System.out.println("2.Bisnis ");
        System.out.print("Pilih : ");
        int pilihKelas = sc.nextInt();
        if(pilihAsal == 1 && pilihTujuan == 2 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[0]*20/100;
            int HK = (hargaE[0]-diskon)*kecil;
            int HD = hargaE[0]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Jakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if (pilihAsal == 1 && pilihTujuan == 3 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[1]*20/100;
            int HK = (hargaE[1]-diskon)*kecil;
            int HD = hargaE[1]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 2 && pilihTujuan == 1 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[0]*20/100;
            int HK = (hargaE[0]-diskon)*kecil;
            int HD = hargaE[0]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Jakarta - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 2 && pilihTujuan == 3 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[2]*20/100;
            int HK = (hargaE[2]-diskon)*kecil;
            int HD = hargaE[2]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Jakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 3 && pilihTujuan == 1 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[1]*20/100;
            int HK = (hargaE[1]-diskon)*kecil;
            int HD = hargaE[1]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Surabaya - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 3 && pilihTujuan == 2 && pilihKelas == 1){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaE[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println("");
            int dewasa = tiket - kecil;
            int diskon = hargaE[2]*20/100;
            int HK = (hargaE[2]-diskon)*kecil;
            int HD = hargaE[2]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Ekonomi");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Surabaya - Jakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }else if(pilihAsal == 1 && pilihTujuan == 2 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta  - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[0]*20/100;
            int HK = (hargaB[0]-diskon)*kecil;
            int HD = hargaB[0]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Jakarta (Pulang - Pergi)");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 1 && pilihTujuan == 3 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Yogyakarta  - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[1]*20/100;
            int HK = (hargaB[1]-diskon)*kecil;
            int HD = hargaB[1]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Yogyakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 2 && pilihTujuan == 1 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta  - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[0]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[0]*20/100;
            int HK = (hargaB[0]-diskon)*kecil;
            int HD = hargaB[0]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Jakarta - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 2 && pilihTujuan == 3 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Jakarta  - Surabaya");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[2]*20/100;
            int HK = (hargaB[2]-diskon)*kecil;
            int HD = hargaB[2]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Jakarta - Surabaya");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 3 && pilihTujuan == 1 && pilihKelas == 2){
           System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya  - Yogyakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[1]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[1]*20/100;
            int HK = (hargaB[1]-diskon)*kecil;
            int HD = hargaB[1]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Surabaya - Yogyakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else if(pilihAsal == 3 && pilihTujuan == 2 && pilihKelas == 2){
            System.out.println("-----------[ Rute Penerbangan Anda ]-------------");
            System.out.println("");
            System.out.println("Surabaya  - Jakarta");
            System.out.println("Dengan Harga tiket : Rp."+hargaB[2]);
            System.out.println("");
            System.out.println("|Usia 1 - 12 (Anak Kecil)  Mendapat diskon 20 % |");
            System.out.println("|     Usia 12+ (Dewasa) harga tiket normal      |");
            System.out.println("");
            System.out.print("Jumlah tiket Yang Dipesan : ");
            int tiket = sc.nextInt();
            System.out.print("jumlah penumpang Anak Kecil : ");
            int kecil = sc.nextInt();
            System.out.println(" ");
            int dewasa = tiket - kecil;
            int diskon = hargaB[2]*20/100;
            int HK = (hargaB[2]-diskon)*kecil;
            int HD = hargaB[2]*dewasa;
            int TH = (HK+HD)*2;
            System.out.println("---------[ Hasil Pemesananan Tiket Pesawat ]------- \n");
            printArray();
            System.out.println("kelas maskapai : Bisnis");
            System.out.println("Tanggal Keberangkatan : "+tanggalK);
            System.out.println("Tanggal Pulang : "+tanggalP);
            System.out.println("Tujuan Penerbangan : Surabaya - Jakarta");
            System.out.println("Jumlah tiket yang di pesan : "+tiket);
            System.out.println("Dewasa : "+dewasa);
            System.out.println("Anak kecil : "+kecil);
            System.out.println("Total harga Tiket Penerbangan : Rp. "+TH);
            System.out.println("-------------------------------------------------");
            System.out.println("-------------------------------------------------\n");
        }
        else{
            System.out.println("Maaf,inputan anda salah");
        }
        }
        else{
            System.out.println("MAAF SALAH INPUTAN");
        }
        
    }
    
    public static void push(String nama,String telp,String TL,String Kelamin) {
            Stack[top][0]=nama;
            Stack[top][1]=telp;
            Stack[top][2]=TL;
            Stack[top][3]= Kelamin;
            top++;
    }
    public static void pop(){
        top--;
        Stack[top][0] = null;
        Stack[top][1] = null;
        Stack[top][2] = null;
        Stack[top][3] = null;
    }
    public static void pendaftaran(){
        System.out.println("kelengkapan data diri penumpang juga membantu Anda dalam kenyamanan perjalanan");
        for (int i = 0; i  < 1; i++) {
        System.out.print("\nNama Anda : ");
        String nama = sc.nextLine();
        System.out.print("Nomor Telepon : ");
        String telp = sc.nextLine();
        System.out.print("Tanggal Lahir : ");
        String  TTL = sc.nextLine();
        System.out.print("Jenis Kelamin (P/L) : ");
        String Kelamin = sc.nextLine();
        push (nama,telp,TTL,Kelamin);
        }
    }
    public static void printArray() {
        for (int i = 0; i < 1; i++) {
            System.out.println("Nama : "+Stack[i][0]);
            System.out.println("No telepon : "+Stack[i][1]);
            System.out.println("Tempat Tanggal Lahir : "+Stack[i][2]);
            System.out.println("Jenis Kelamin (P/L) : "+Stack[i][3]);
            System.out.println("\n");
        }
    }
}



